RealEstate.WebUI/Areas/Admin/Controllers/WhoWeAreController.cs
using Microsoft.AspNetCore.Mvc;
using RealEstate.WebUI.ApiClients.Abstracts;
using RealEstate.WebUI.Dtos.WhoWeAreDetailDtos;

namespace RealEstate.WebUI.Areas.Admin.Controllers;

[Area("Admin")]
public class WhoWeAreController : Controller
{
    private readonly IWhoWeAreApiClient _apiClient;

    public WhoWeAreController(IWhoWeAreApiClient whoWeAreApiClient)
    {
        _apiClient = whoWeAreApiClient;
    }

    public async Task<IActionResult> Index()
    {
        List<ResultWhoWeAreDetailDto> result = await _apiClient.GetAllAsync();
        if (result is not null)
            return View(result);
        return View();
    }

    [HttpGet]
    public IActionResult CreateWhoWeAreDetail()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> CreateWhoWeAreDetail(CreateWhoWeAreDetailDto whoWeAreDetailDto)
    {
        await _apiClient.AddAsync(whoWeAreDetailDto);
        return RedirectToAction(nameof(Index));
    }

    public async Task<IActionResult> DeleteWhoWeAreDetail(int id)
    {
        bool isSuccess = await _apiClient.DeleteAsync(id);
        if (isSuccess)
            return RedirectToAction(nameof(Index));
        return View();
    }

    [HttpGet]
    public async Task<IActionResult> UpdateWhoWeAreDetail(int id)
    {
        UpdateWhoWeAreDetailDto result = await _apiClient.GetUpdateAsync(id);
        if (result is not null)
            return View(result);
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> UpdateWhoWeAreDetail(UpdateWhoWeAreDetailDto whoWeAreDetailDto)
    {
        bool isSuccess = await _apiClient.UpdateAsync(whoWeAreDetailDto);
        if (isSuccess)
            return RedirectToAction(nameof(Index));
        return View();
    }
}

RealEstate.WebUI/Areas/Admin/Views/WhoWeAre/CreateWhoWeAreDetail.cshtml
@model CreateWhoWeAreDetailDto

@{
    ViewData["Title"] = "Biz Kimiz? Oluştur";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="col-12">
    <div class="bg-light rounded h-100 p-4">
        <h6 class="mb-4">Yeni Biz Kimiz Kaydı</h6>
        <form method="post">
            <label asp-for="Title">Başlık</label>
            <input type="text" asp-for="Title" class="form-control" />
            <br />
            <label asp-for="Subtitle">Alt Başlık</label>
            <input type="text" asp-for="Subtitle" class="form-control" />
            <br />
            <label asp-for="Description1">Açıklamalar</label>
            <textarea style="height: 150px;" asp-for="Description1" class="form-control" id="floatingTextarea"></textarea>
            <br />
            <label asp-for="Description2">Diğer Bilgiler</label>
            <textarea style="height: 150px;" asp-for="Description2" class="form-control" id="floatingTextarea"></textarea>
            <br />
            <button class="btn btn-outline-success">Kaydet</button>
        </form>
    </div>
</div>

RealEstate.WebUI/Areas/Admin/Views/WhoWeAre/Index.cshtml
@model List<ResultWhoWeAreDetailDto>

@{
    ViewData["Title"] = "Biz Kimiz?";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="col-12">
    <div class="bg-light rounded h-100 p-4">
        <h6 class="mb-4">Biz Kimiz</h6>
        <div class="table-responsive">
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Başlık</th>
                        <th scope="col">Alt Başlık</th>
                        <th scope="col">Açıklamalar</th>
                        <th scope="col">Diğer Bilgiler</th>
                        <th scope="col" colspan="2">İşlemler</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (ResultWhoWeAreDetailDto entity in Model)
                    {
                        <tr>
                            <th scope="row">@entity.WhoWeAreDetailId</th>
                            <td>@entity.Title</td>
                            <td>@entity.Subtitle</td>
                            <td>@entity.Description1</td>
                            <td>@entity.Description2</td>
                            <td><a asp-area="Admin" asp-controller="WhoWeAre" asp-action="UpdateWhoWeAreDetail" asp-route-id="@entity.WhoWeAreDetailId" class="btn btn-outline-primary">Güncelle</a></td>
                            <td><a asp-area="Admin" asp-controller="WhoWeAre" asp-action="DeleteWhoWeAreDetail" asp-route-id="@entity.WhoWeAreDetailId" class="btn btn-outline-danger">Sil</a></td>
                        </tr>
                    }
                </tbody>
            </table>
            <a asp-area="Admin" asp-controller="WhoWeAre" asp-action="CreateWhoWeAreDetail" class="btn btn-outline-info">Yeni Detay</a>
        </div>
    </div>
</div>

RealEstate.WebUI/Areas/Admin/Views/WhoWeAre/UpdateWhoWeAreDetail.cshtml
@model UpdateWhoWeAreDetailDto

@{
    ViewData["Title"] = "Biz Kimiz? Güncelle";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="col-12">
    <div class="bg-light rounded h-100 p-4">
        <h6 class="mb-4">Yeni Biz Kimiz Kaydı</h6>
        <form method="post">
            <input type="hidden" asp-for="WhoWeAreDetailId" />
            <label asp-for="Title">Başlık</label>
            <input type="text" asp-for="Title" class="form-control" />
            <br />
            <label asp-for="Subtitle">Alt Başlık</label>
            <input type="text" asp-for="Subtitle" class="form-control" />
            <br />
            <label asp-for="Description1">Açıklamalar</label>
            <textarea style="height: 150px;" asp-for="Description1" class="form-control" id="floatingTextarea"></textarea>
            <br />
            <label asp-for="Description2">Diğer Bilgiler</label>
            <textarea style="height: 150px;" asp-for="Description2" class="form-control" id="floatingTextarea"></textarea>
            <br />
            <button class="btn btn-outline-success">Kaydet</button>
        </form>
    </div>
</div>